UGS-GIO/geohaz-v2

- .github/workflows/firebase-hosting-merge.yml
- package-lock.json
- package.json
- release.config.cjs
@clintonlunn Please review. 
I installed semantic-release and its plugins. Added a config file and added code for releases in the merge yaml
> feat: add semantic release to github action workflow (ALL-1535)

- release.config.cjs
> fix: release branch changed in config from main to master

- .github/workflows/firebase-hosting-merge.yml
we accidentally removed the deployment logic that deployed develop branch to dev environment. this adds a conditional if statement to run semantic-release logic if on master branch, otherwise just run the deploy
> fix: add conditional release logic so we can also deploy develop again (ALL-1535)

- src/components/widgets/LayerlistAccordion.tsx
> refactor: comment out sidebar legend

- src/components/widgets/MapWidgets.tsx
> feat: make legend expandable

- package-lock.json
- package.json
- src/components/LayerControls.tsx
- src/components/SidebarComponents/Layers.tsx
- src/components/widgets/LayerlistAccordion.tsx
- src/contexts/MapProvider.tsx
- src/index.css
> feat: add a tooltip with description for each imported layer

- src/components/SidebarComponents/Info.tsx
- src/components/shared/ReadMore.tsx
> feat: adding content to info panel

- package-lock.json
- package.json
- src/components/custom/layer-controls.tsx
- src/components/custom/layerlist-accordion.tsx
- src/components/custom/legend-accordion.tsx
- src/components/ui/toggle.tsx
- src/pages/dashboard/components/map-widgets.tsx
https://github.com/user-attachments/assets/1bec8db0-d9b9-417d-a572-c5b9a979d969
> refactor: move opacity to top of layer controls, trigger legend accordion from outside of component, update mobile layout for buttons

- src/components/sidebar/map-configurations.tsx
- src/hooks/use-arcgis-widget.tsx
- src/index.css
> refactor: align map configuration toggle colors with theme, make buttons shorter

- package-lock.json
- package.json
- src/components/nav.tsx
- src/components/sidebar/info.tsx
- src/data/website-info.tsx
> refactor: sticky Start Exploring and Data Disclaimer buttons to bottom of info panel

- src/components/ui/accordion.tsx
https://github.com/user-attachments/assets/26b58b66-908d-480e-aa4e-8761e77240fb
> fix: add classes so that the accordion chevron will rotate when data-state changes

- src/components/custom/layer-controls.tsx
> refactor: make layercontrols labels hidden on mobile

- src/components/custom/button.tsx
- src/components/custom/layer-controls.tsx
- src/components/ui/toggle.tsx
> Mobile layer controls

- src/components/custom/layer-controls.tsx
> refactor: make zoom, info, legend buttons same width, add toggle buttons back

- package-lock.json
- package.json
- src/components/custom/legend-accordion.tsx
- src/context/map-provider.tsx
- src/hooks/use-custom-layerlist.tsx
- src/hooks/use-legend-preview.tsx
- src/lib/legend/symbol-generator.ts
- src/lib/mapping-utils.ts
- src/lib/types/geoserver-types.ts
- src/main.tsx
> refactor: remove layerlst viewmodel from setting activelayers, fix symbol generation

- src/pages/hazards/data/layers.tsx
> refactor: remove flood and debris layer, replace with alluvialfan layer

- src/components/custom/popups/popup-content-with-pagination.tsx
- src/pages/hazards/data/layers.tsx
> fix: add popupfields and related tables for karstfeatures and erosionhazardzone

- src/components/custom/legend-accordion.tsx
- src/lib/legend/symbol-generator.ts
- src/pages/hazards/data/layers.tsx
> fix: make 24kquads symbology work with stroke

- src/components/custom/popups/popup-content-display.tsx
- src/hooks/use-related-table.tsx
- src/lib/mapping-utils.ts
- src/lib/types/mapping-types.ts
- src/pages/ccus/data/layers.tsx
- src/pages/hazards/data/layers.tsx
> feat(ccus): add related tables for ccus wells

- src/components/custom/popups/popup-content-with-pagination.tsx
- src/components/custom/popups/popup-drawer.tsx
- src/pages/hazards/data/popup-buttons.tsx
> refactor: make max height 50vh for mobile, 85vh desktop, reduce popup paddings

- src/components/ui/switch.tsx
- src/hooks/use-custom-layerlist.tsx
- src/hooks/use-layer-visibility-manager.tsx
> feat: add a select all checkbox in layerlist, add switch for grouplayers

- src/pages/ccus/data/layers.tsx
> feat(ccus): add 500k faults layer

- src/pages/ccus/data/layers.tsx
> refactor(ccus): change popup name from Reservoir Rocks to Resevoir Age

- src/components/custom/popups/popup-content-display.tsx
- src/components/custom/popups/popup-content-with-pagination.tsx
- src/components/custom/popups/popup-drawer.tsx
- src/hooks/use-map-interactions.tsx
- src/lib/types/mapping-types.ts
- src/pages/ccus/components/map-container.tsx
- src/pages/ccus/data/layers.tsx
- src/pages/hazards/components/map-container.tsx
- src/pages/hazards/data/layers.tsx
> feat: add a transform and decimalplaces property to popupFields

- src/assets/basemap-icons.tsx
> fix: change stroke-width to camelcase to fix warning

- src/components/custom/popups/popup-content-display.tsx
- src/components/custom/popups/popup-content-with-pagination.tsx
- src/hooks/use-map-interactions.tsx
- src/hooks/use-related-table.tsx
- src/lib/mapping-utils.ts
- src/lib/types/mapping-types.ts
- src/pages/ccus/components/map-container.tsx
- src/pages/hazards/components/map-container.tsx
- src/pages/hazards/data/layers.tsx
> feat: adding an optional raster value to the popup

- src/components/custom/popups/popup-content-display.tsx
- src/components/custom/popups/popup-drawer.tsx
> refactor: popup close button on bottom, add to top right

- src/components/top-nav.tsx
> refactor: change basemap name, remove streets relief

- src/pages/hazards/data/layers.tsx
> refactor: convert all polygons to 75% opacity for map load

- src/components/nav.tsx
> refactor: make navbar tooltip text color darker on light mode

- src/components/sidebar.tsx
- src/pages/hazards/data/sidelinks.tsx
https://github.com/user-attachments/assets/00d3a5cf-2906-4c2b-be5f-d63a98161b6e
> refactor: remove nav link to https://geology.utah.gov/, make logo clickable to redirect user

- src/hooks/use-custom-layerlist.tsx
https://github.com/user-attachments/assets/286d161b-2ba8-4027-89ca-24efd1c69506
> fix: prevent graphics layer from being added to layerlist

- src/components/sidebar/info.tsx
- src/components/sidebar/report-generator.tsx
- src/pages/hazards/data/page-info.tsx
> refactor: change page info for (hazards)

- src/components/search-bar.tsx
> refactor: update pgfeatureserv url (hazards)

- src/components/sidebar/info.tsx
- src/components/sidebar/report-generator.tsx
- src/hooks/use-get-page-info.tsx
- src/pages/ccus/data/page-info.tsx
- src/pages/hazards/data/page-info.tsx
- src/pages/minerals/data/page-info.tsx
> fix(hazards): fix acknowledgments spelling, update report generator report link

- src/lib/legend/symbol-generator.ts
> refactor(common): refactor to differentiate between simple symbol and picture symbol

- src/components/custom/popups/popup-content-display.tsx
> feat(common): implement 'custom' field to create a paragraph view or concatenate fields together

- src/hooks/use-related-table.tsx
- src/lib/types/mapping-types.ts
- src/pages/ccus/data/layers.tsx
> Wells related table order

- src/pages/wetlands/data/layers.tsx
> Revert "feat(wetlands): added popup info"

- src/pages/wetlands/data/layers.tsx
Opacity settings added to wetlands
> feat(wetlands): added opacity settings

- src/components/custom/popups/popup-content-display.tsx
- src/hooks/use-related-table.tsx
- src/lib/types/mapping-types.ts
- src/pages/ccus/data/layers.tsx
- src/pages/hazards/data/layers.tsx
- src/pages/minerals/data/layers.tsx
- src/pages/wetlands/data/layers.tsx
> feat(ccus): added popup attributes

- src/pages/ccus/data/layers.tsx
> feat(ccus): add geothermal powerplants layer

- src/lib/mapping-utils.ts
- src/pages/ccus/data/layers.tsx
> refactor(ccus): implement map-image legend for sitla landownership
